### ISSUE TITLE
TC4 Protocol with Max31856

### ISSUE THREAD

**Issue by thedimou** [FilePhil/TC4-Emulator#1]
Hi there,
I am having some troubles making my Arduino project with 3 x MAX31856 work with artisan. Tried to follow your project with some differentiations according to MAX31856 library.

`
#include <Arduino.h>
#include <Adafruit_MAX31856.h>
#include <SPI.h>

Adafruit_MAX31856 maxthermoET = Adafruit_MAX31856(4, 8, 9, 3);
Adafruit_MAX31856 maxthermoBT = Adafruit_MAX31856(5, 8, 9, 3);
Adafruit_MAX31856 maxthermoAT = Adafruit_MAX31856(6, 8, 9, 3);

void setup() {
  Serial.begin(9600);
  while (!Serial) delay(10);
  Serial.println("MAX31856 thermocouple test");

  if (!maxthermoET.begin()) {
    Serial.println("Could not initialize 1st thermocouple.");
    while (1) delay(10);
  }

if (!maxthermoBT.begin()) {
    Serial.println("Could not initialize 2nd thermocouple.");
    while (1) delay(10);
  }

if (!maxthermoBT.begin()) {
    Serial.println("Could not initialize 3rd thermocouple.");
    while (1) delay(10);
  }  

  maxthermoET.setThermocoupleType(MAX31856_TCTYPE_K);
  maxthermoBT.setThermocoupleType(MAX31856_TCTYPE_K);
  maxthermoAT.setThermocoupleType(MAX31856_TCTYPE_K);

  maxthermoET.setConversionMode(MAX31856_ONESHOT_NOWAIT);
  maxthermoBT.setConversionMode(MAX31856_ONESHOT_NOWAIT);
  maxthermoAT.setConversionMode(MAX31856_ONESHOT_NOWAIT);

}

void loop() {
  // trigger a conversion, returns immediately
  maxthermoET.triggerOneShot();
  maxthermoBT.triggerOneShot();
  maxthermoAT.triggerOneShot();
  
  delay(500); // replace this with whatever

  // check for conversion complete and read temperature
  
  if (maxthermoET.conversionComplete()) {
    Serial.print(maxthermoET.readThermocoupleTemperature());
  } else {
    Serial.println("Conversion not complete!");
  }

  if (maxthermoBT.conversionComplete()) {
    Serial.print(maxthermoBT.readThermocoupleTemperature());
  } else {
    Serial.println("Conversion not complete!");
  }

  if (maxthermoAT.conversionComplete()) {
    Serial.print(maxthermoAT.readThermocoupleTemperature());
  } else {
    Serial.println("Conversion not complete!");
  }
}
`

**Comment by FilePhil** [comment]
Hey,
Artisan/TC4 does support the direct sending of Values.
Artisan sends  Commands to request settings or Data. The Values must be in a fixed Order and Syntax.
See the "handleSerialCommand" and "Command_READ" functions.

The "0.00" in the "Command_READ" Functions are unused Data Channels, that can be replaced by actual Values. The First Channel is used for environmental Temperatur and can not be used freely.

Also any Serial output than the expected "#OK.."  and the output of the "Command_READ" will cause Issues in Artisan.

**Comment by thedimou** [comment]
Thank you for your reply. I have read some of the artisan code and figured out how to send data, but didn't know that anything else of a msg except the "#ok" could cause problems. So I'm going to replace the test msgs with the ok.

Something last, the data (3 temps) i send and read in artisan, have the following form:
0.00,35.5,36.5,35.4,0.00 //end of line

If i needed a fourth temp how should i form them?
